AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  lambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: "*"
          PolicyName: lambda1Logging
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - health:DescribeEventTypes
                Effect: Allow
                Resource: "*"
          PolicyName: lambda1Health
  
  eventTypeCodesTypeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda-code/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: !GetAtt lambdaIAMRole.Arn
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /eventTypeCodesType
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  eventTypeCodesTypeApi:
    Description: "API Gateway endpoint URL for Prod stage for eventTypeCodesType function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/eventTypeCodesType/"
  eventTypeCodesTypeFunction:
    Description: "eventTypeCodesType Function ARN"
    Value: !GetAtt eventTypeCodesTypeFunction.Arn
  eventTypeCodesTypeFunctionIamRole:
    Description: "Implicit IAM Role created for eventTypeCodesType Function"
    Value: !GetAtt lambdaIAMRole.Arn
